---
### Required Configuration ###
#
# Your Full Name
user_name: ""
# Your email address
user_email: ""
#
### End Required Configuration ###

# General configuration options
configure_dotfiles: yes
configure_git: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: no

downloads: ~/.ansible-downloads/

# User-defined dotfile repo
dotfiles_repo: ""
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files: []

# Install user-defined packages (beyond core required packages for SinglePlatform)
homebrew_additional_packages: []
homebrew_cask_additional_apps: []

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_additional_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_additional_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_additional_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_additional_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Install user-defined packages from apple store
mas_additional_installed_apps: []
mas_email: ""
mas_password: ""

