---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/davidpanofsky/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/envs/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .SpaceVim.d/init.vim
  - .osx

homebrew_upgrade_all_packages: True
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ack
  - autoconf
  - bash-completion
  - ccache
  - coreutils
  - fd
  - fdupes
  - fontconfig
  - fzf
  - gettext
  - git
  - git-secrets
  - gnu-sed
  - gpg
  - httpie
  - jq
  - lftp
  - links
  - nmap
  - openssh
  - openssl
  - parallel
  - psutils
  - pv
  - pwgen
  - pyenv
  - pyenv-ccache
  - pyenv-pip-migrate
  - pyenv-virtualenv
  - readline
  - sqlite
  - ssh-copy-id
  - sslscan
  - tcptraceroute
  - tmux
  - tmux-cssh
  - vagrant-completion
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adobe-acrobat-pro
  - adobe-acrobat-reader
  - air-connect
  - amethyst
  - android-file-transfer
  - android-platform-tools
  - aws-vault
  - chrome-devtools
  - chrome-remote-desktop-host
  - cyberduck
  - datagrip
  - docker
  - docker
  - docker-toolbox
  - dropbox
  - dropbox
  - firefox
  - font-dejavusansmono-nerd-font
  - font-droidsansmono-nerd-font
  - font-hack-nerd-font
  - github
  - gitup
  - google-chat
  - google-chrome
  - google-drive-file-stream
  - google-hangouts
  - hipchat
  - iterm2
  - jira-client
  - lastpass
  - macpass
  - mysql-client
  - mysql-connector-python
  - mysql-shell
  - mysql-utilities
  - mysqlworkbench
  - noti
  - postman
  - pycharm
  - redis-app
  - rsyncosx
  - sonoair
  - spotify
  - sqlexplorer
  - sqlworkbenchj
  - sublime-text
  - synergy
  - time-out
  - trim-enabler
  - utc-menu-clock
  - vagrant
  - vagrant-manager
  - virtualbox
  - virtualc64
  - wireshark
  - xaos

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 406056744, name: "Evernote (6.13.1)" }
  - { id: 405399194, name: "Kindle (1.21.1)" }
  - { id: 585829637, name: "Todoist (7.0.9)" }
  - { id: 425955336, name: "Skitch (2.8)" }
  - { id: 1187772509, name: "stts (1.1.8)" }
  - { id: 865500966, name: "feedly (1.1)" }
  - { id: 948415170, name: "Pushbullet (4)" }
  - { id: 715768417, name: "Microsoft Remote Desktop (8.0.27325)" }
  - { id: 404010395, name: "TextWrangler (5.5.2)" }
  - { id: 568494494, name: "Pocket (1.6.2)" }
mas_email: "apple@rudybear.com"
mas_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30623162353064376432386533646261316162623336373166626436653331633039343537383631
          3332666236643734333936383131306565366266333438310a653964393231303261643036376437
          30326238363435306665343866333066383163653063383865636464393962316433383038333831
          6633636161343436390a363334626639356364306666383336303931666263306235373734616335
          35373138313237353437646336366538633864333761366337613538303136633236

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
   - pip
   - wheel
   - setuptools
   - virtualenv
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
