---
# Copy default dotfiles into place
- name: Copy default SP dotfiles
  copy:
    src: files/dotfiles/
    dest: "~"
    force: no
    mode: 0755
  tags: dotfiles

- name: Include SP bash profile
  lineinfile:
    path: ~/.bash_profile
    line: . ~/.bash_profile_sp
    insertbefore: BOF
    create: yes
