---
# Configure GIT
- name: Set git user name
  git_config:
    name: user.name
    scope: global
    value: '{{ ansible_user_gecos }}'

- name: Set git email address
  git_config:
    name: user.email
    scope: global
    value: '{{ user_email }}'

#- name: Read SSH public key to authorize
#  shell: cat ~/.ssh/id_rsa.pub
#  register: ssh_pub_key
#
#- name: Authorize key with GitHub
#  local_action:
#    module: github_key
#    name: SinglePlatform
#    token: '{{ github_access_token }}'
#    pubkey: '{{ ssh_pub_key.stdout }}'
#
- name: Ensure vagrant hostmanager plugin is installed
  shell: vagrant plugin install vagrant-hostmanager

- name: Ensure singleplatform repositories are cloned locally.
  git:
    repo: "sp:{{ item }}"
    dest: "{{ sp_git_repos_local_directory }}/{{ item }}"
    recursive: yes
  become: no
  with_items: "{{ sp_git_repos }}"
