---
# Configure GIT
- name: Set git user name
  git_config:
    name: user.name
    scope: global
    value: '{{ ansible_user_gecos }}'
  tags: git

- name: Set git email address
  git_config:
    name: user.email
    scope: global
    value: '{{ user_email }}'
  tags: git

#- name: Read SSH public key to authorize
#  shell: cat ~/.ssh/id_rsa.pub
#  register: ssh_pub_key
#
#- name: Authorize key with GitHub
#  local_action:
#    module: github_key
#    name: SinglePlatform
#    token: '{{ github_access_token }}'
#    pubkey: '{{ ssh_pub_key.stdout }}'
#
- name: Ensure vagrant hostmanager plugin is installed
  shell: vagrant plugin install vagrant-hostmanager

- name: Ensure pyenv has correct python version installed
  shell: pyenv install -s "{{ default_python_version }}"

- name: Configure pyenv to use correct python version
  shell: pyenv global "{{ default_python_version }}"

- name: Ensure singleplatform repositories are cloned locally.
  git:
    repo: "sp:{{ item }}"
    dest: "{{ sp_git_repos_local_directory }}/.{{ item }}"
    recursive: yes
    bare: yes
  become: no
  with_items: "{{ sp_git_repos }}"

- name: Ensure singleplatform repositories are available locally.
  git:
    repo: "sp:{{ item }}"
    dest: "{{ sp_git_repos_local_directory }}/{{ item }}"
    recursive: yes
    reference: "{{ sp_git_repos_local_directory }}/.{{ item }}"
    bare: no
  become: no
  with_items: "{{ sp_git_repos }}"

- name: Create pyenv virtualenv for ansible
  shell: pyenv virtualenv "{{ default_python_version }}" ansible

- name: Lookup pyenv root
  shell: pyenv root
  register: pyenv_root

- name: Install requirements into ansible virtualenv
  shell: "{{ pyenv_root.stdout }}/versions/ansible/bin/pip install -r {{ sp_git_repos_local_directory }}/ansible/requirements.txt"

- name: Configure pyenv local for ansible
  copy:
    content: "ansible"
    dest: "{{ sp_git_repos_local_directory }}/ansible/.python-version"
    mode: 0644
